#!/bin/bash

#This script assumes that ConnextCMS is installed in the users home directory,
#aliased with the ~ symbol. Edit the directory paths below if this assumption is invalid.

echo Preparing to copy into myCMS directory...

# Copy the keystone.js file
cp keystone/core/keystone.js ~/myCMS/

echo Copying Keystone Models
cp keystone/models/*.js ~/myCMS/models/

echo Copying Keystone API Routes
cp keystone/routes/*.js ~/myCMS/routes/
cp -r keystone/routes/api ~/myCMS/routes/
cp keystone/routes/views/*.js ~/myCMS/routes/views/

echo Copying Keystone Views
cp keystone/templates/views/*.hbs ~/myCMS/templates/views/
cp keystone/templates/views/layouts/*.hbs ~/myCMS/templates/views/layouts/

# Allow CORS for the Admin API - Used for development purposes. Comment this out for production.
cp keystone/core/createDynamicRouter.js ~/myCMS/node_modules/keystone/admin/server/app/

# Remove the CSRF token requirement in the Keystone Admin API - Used for development purposes. Comment this out for production.
cp keystone/core/signin.js ~/myCMS/node_modules/keystone/admin/server/api/session/signin.js
cp keystone/core/signout.js ~/myCMS/node_modules/keystone/admin/server/api/session/signout.js

# Replace the default index.js router file that comes with ConnextCMS. This allows us to create new users.
cp keystone/routes/index.js ~/myCMS/routes/
cp keystone/routes/api/users.js ~/myCMS/routes/api/

# Copy package.json and install dependencies
#cp package.json ~/myCMS/
#cd ~/myCMS/
#npm install
#cd -

#Customize the below .json files
echo Copying settings.json files
cp publicsettings.json ~/myCMS/public/js/
cp privatesettings.json ~/myCMS/private/

#THIS SHOULD BE LAST CODE BLOCK EXECUTED
echo Copying public directory
cp -rP public ~/myCMS/
#For docker/nginx config, copy the public file to a directory accessibly by the host system
cp -rP ~/myCMS/public ~/
